# Generated by Django 4.1.4 on 2023-02-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('Vente', 'Vente'), ('Echange', 'Echange'), ('Location', 'Location'), ('Location_Vacances', 'Location_Vacances')], max_length=50, null=True)),
                ('type', models.CharField(max_length=200)),
                ('surface', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('prix', models.IntegerField(null=True)),
                ('wilaya', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'read'), ('unread', 'unread')], max_length=50, null=True)),
                ('contenu', models.TextField(max_length=250)),
                ('userSource', models.EmailField(max_length=254, null=True)),
                ('userDestination', models.EmailField(max_length=254, null=True)),
                ('date', models.DateField(null=True)),
                ('titreAnnance', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='annonce_imgs/')),
                ('idAnnance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonce_imgs', to='app_annance.annance')),
            ],
        ),
        migrations.AddField(
            model_name='annance',
            name='idAnnanceur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_annance.profile'),
        ),
    ]
