# Generated by Django 4.1.4 on 2023-02-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_annance', '0005_remove_annance_idannanceur_remove_photo_idannance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='annance',
            name='urlgoogleMap',
            field=models.URLField(null=True),
        ),
    ]
